name: A workflow for building and testing libCellML
on: push

jobs:
  build:

    strategy:
      matrix:
        os: [ubuntu-16.04, ubuntu-18.04]
        build_type: [Debug, Release]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@master
    - name: configure
      run: cmake -DBUILD_TYPE=${{ matrix.build_type }} .
    - name: build
      run: cmake --build . --config ${{ matrix.build_type }}
    - name: test
      run: ctest -C ${{ matrix.build_type }}

