name: CI

on:
  push:
  pull_request:
    branches: [ main ]
  workflow_dispatch:
  workflow_call:
    inputs:
      ref:
        required: true
        type: string

jobs:
  cpp_python:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: 'Windows static - C++'
            os: windows-2022
            python_bindings: OFF
            additional_cmake_options: -DLibXml2_DIR="C:\libxml2\libxml2-2.9.10\CMake" -DZLIB_DIR="C:\zlib\lib\cmake\ZLIB-1.2.12"
    steps:
      - name: Check out libCellML
        uses: actions/checkout@v6
        with:
          ref: ${{ inputs.ref || github.ref }}
      - name: Install Python (if needed)
        if: ${{ matrix.python_bindings == 'ON' }}
        uses: actions/setup-python@v6
        with:
          python-version: '3.13'
      - name: Install CMake and Ninja
        uses: lukka/get-cmake@latest
      - name: Configure MSVC (Windows only)
        if: ${{ runner.os == 'Windows' }}
        uses: TheMrMilchmann/setup-msvc-dev@v4
        with:
          arch: x64
      - name: Install libxml2 (Windows only)
        if: ${{ runner.os == 'Windows' }}
        run: |
          cd C:\
          curl -L https://github.com/cellml/gha/releases/download/gha/libxml2-Windows.tar.gz -o libxml2.tar.gz -s
          tar -xzf libxml2.tar.gz
          dir C:\libxml2\bin
          dir C:\libxml2\lib
      - name: Install zlib (Windows only)
        if: ${{ runner.os == 'Windows' }}
        run: |
          cd C:\
          curl -L https://github.com/cellml/gha/releases/download/gha/zlib-Windows.tar.gz -o zlib.tar.gz -s
          tar -xzf zlib.tar.gz
          dir C:\zlib\bin
          dir C:\zlib\lib
      - name: Install SWIG (macOS only and if needed)
        if: ${{ runner.os == 'macOS' && matrix.python_bindings == 'ON' }}
        run: brew install swig
      - name: Configure libCellML
        run: cmake -G Ninja -S . -B build -DBINDINGS_PYTHON=${{ matrix.python_bindings }} -DBUILD_SHARED=ON -DCOVERAGE=OFF -DLLVM_COVERAGE=OFF -DMEMCHECK=OFF -DUNIT_TESTS=ON ${{ matrix.additional_cmake_options }}
      - name: Build libCellML
        run: cmake --build build
      - name: Unit testing
        run: |
          cd build
          ctest -C Release --output-on-failure -VV
          #cmake --build build --target test
